auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Blog - FindShine.com
url: http://blog.findshine.com
feed: /atom.xml
author_info: <a href="http://findshine.com/">FanShen</a>
